#!/bin/sh
# Copyright (C) 2006 OpenWrt.org
# Copyright (C) 2010 Vertical Communications

do_mount_root() {
	echo "Before mount_root"
	echo "Set FWUP_STATE_NOK"
	state_cfg set fwup_state 1
	mount_root
	boot_run_hook preinit_mount_root
	[ -f /sysupgrade.tgz ] && {
		echo "- config restore -"
		cd /
		tar xzf /sysupgrade.tgz
	}
	echo "After mount_root"
}

[ "$INITRAMFS" = "1" ] || boot_hook_add preinit_main do_mount_root
