#!/bin/sh

macadd_str=`state_cfg get ethaddr | sed -r 's/://g' | sed 's/^......//'`
password_str=`state_cfg get rkey | awk '{print $1}'`

###SSID
if [ "`uci get wireless.@wifi-iface[0].ssid`" = "" ];then
    uci set wireless.@wifi-iface[0].ssid="JioMesh-$macadd_str"
fi
if [ "`uci get wireless.@wifi-iface[1].ssid`" = "" ];then
    uci set wireless.@wifi-iface[1].ssid="JioMesh-$macadd_str"
fi
if [ "`uci get wireless.@wifi-iface[2].ssid`" = "" ];then
    uci set wireless.@wifi-iface[2].ssid="jioMesh-$macadd_str"
fi
###KEY
if [ "`uci get wireless.@wifi-iface[0].key`" = "" ];then
    ##TODO
    if [ "$password_str" = "" ];then
        uci set wireless.@wifi-iface[0].key="1234567890"
    else
        uci set wireless.@wifi-iface[0].key="$password_str"
    fi
fi
if [ "`uci get wireless.@wifi-iface[1].key`" = "" ];then
    ##TODO
    if [ "$password_str" = "" ];then
        uci set wireless.@wifi-iface[1].key="1234567890"
    else
        uci set wireless.@wifi-iface[1].key="$password_str"
    fi
fi
if [ "`uci get wireless.@wifi-iface[2].key`" = "" ];then
    ##TODO
    if [ "$password_str" = "" ];then
        uci set wireless.@wifi-iface[2].key="1234567890"
    else
        uci set wireless.@wifi-iface[2].key="$password_str"
    fi
fi

uci commit wireless

