#!/bin/sh

macadd_str=`state_cfg get ethaddr | sed -r 's/://g' | sed 's/^......//'`
password_str=`state_cfg get rkey | awk '{print $1}'`

###SSID
if [ "`uci get wireless.@wifi-iface[0].ssid`" = "" ];then
    uci set wireless.@wifi-iface[0].ssid="JioMesh-$macadd_str"
fi
if [ "`uci get wireless.@wifi-iface[1].ssid`" = "" ];then
    uci set wireless.@wifi-iface[1].ssid="JioMesh-$macadd_str"
fi
if [ "`uci get wireless.@wifi-iface[2].ssid`" = "" ];then
    uci set wireless.@wifi-iface[2].ssid="jio-backhaul-$macadd_str"
fi
if [ "`uci get wireless.@wifi-iface[3].ssid`" = "" ];then
    uci set wireless.@wifi-iface[3].ssid="jio-backhaul-$macadd_str"
fi
if [ "`uci get wireless.@wifi-iface[4].ssid`" = "" ];then
    uci set wireless.@wifi-iface[4].ssid="jio-backhaul-$macadd_str"
fi
if [ "`uci get wireless.@wifi-iface[5].ssid`" = "" ];then
    uci set wireless.@wifi-iface[5].ssid="jio-backhaul-$macadd_str"
fi
if [ "`uci get wireless.@wifi-iface[6].ssid`" = "" ];then
    uci set wireless.@wifi-iface[6].ssid="JioMesh-guest"
fi
if [ "`uci get wireless.@wifi-iface[7].ssid`" = "" ];then
    uci set wireless.@wifi-iface[7].ssid="JioMesh-guest"
fi

###KEY
if [ "`uci get wireless.@wifi-iface[0].key`" = "" ];then
    ##TODO
    if [ "$password_str" = "" ];then
        uci set wireless.@wifi-iface[0].key="1234567890"
    else
        uci set wireless.@wifi-iface[0].key="$password_str"
    fi
fi
if [ "`uci get wireless.@wifi-iface[1].key`" = "" ];then
    ##TODO
    if [ "$password_str" = "" ];then
        uci set wireless.@wifi-iface[1].key="1234567890"
    else
        uci set wireless.@wifi-iface[1].key="$password_str"
    fi
fi
if [ "`uci get wireless.@wifi-iface[2].key`" = "" ];then
    ##TODO
    if [ "$password_str" = "" ];then
        uci set wireless.@wifi-iface[2].key="1234567890"
    else
        uci set wireless.@wifi-iface[2].key="$password_str"
    fi
fi
if [ "`uci get wireless.@wifi-iface[3].key`" = "" ];then
    ##TODO
    if [ "$password_str" = "" ];then
        uci set wireless.@wifi-iface[3].key="1234567890"
    else
        uci set wireless.@wifi-iface[3].key="$password_str"
    fi
fi
if [ "`uci get wireless.@wifi-iface[4].key`" = "" ];then
    ##TODO
    if [ "$password_str" = "" ];then
        uci set wireless.@wifi-iface[4].key="1234567890"
    else
        uci set wireless.@wifi-iface[4].key="$password_str"
    fi
fi
if [ "`uci get wireless.@wifi-iface[5].key`" = "" ];then
    ##TODO
    if [ "$password_str" = "" ];then
        uci set wireless.@wifi-iface[5].key="1234567890"
    else
        uci set wireless.@wifi-iface[5].key="$password_str"
    fi
fi

uci commit wireless

