#!/bin/sh

macadd_str=`state_cfg get ethaddr | sed -r 's/://g' | sed 's/^......//'`
rmacaddr=`state_cfg get rmac`
rmac2addr=`state_cfg get rmac2`
password_str=`state_cfg get rkey | awk '{print $1}'`
###MAC
if [ "`uci get wireless.@wifi-device[0].macaddr`" = "" ];then
    uci set wireless.@wifi-device[0].macaddr="$rmacaddr"
fi
if [ "`uci get wireless.@wifi-device[1].macaddr`" = "" ];then
    uci set wireless.@wifi-device[1].macaddr="$rmac2addr"
fi
###SSID
if [ "`uci get wireless.@wifi-iface[0].ssid`" = "" ];then
    uci set wireless.@wifi-iface[0].ssid="JioMesh-$macadd_str"
fi
if [ "`uci get wireless.@wifi-iface[1].ssid`" = "" ];then
    uci set wireless.@wifi-iface[1].ssid="JioMesh-$macadd_str"
fi
if [ "`uci get wireless.@wifi-iface[2].ssid`" = "" ];then
    uci set wireless.@wifi-iface[2].ssid="JioMesh-$macadd_str"
fi
###KEY
if [ "`uci get wireless.@wifi-iface[0].key`" = "" ];then
    ##TODO
    if [ "$password_str" = "" ];then
        uci set wireless.@wifi-iface[0].key="1234567890"
    else
        uci set wireless.@wifi-iface[0].key="$password_str"
    fi
fi
if [ "`uci get wireless.@wifi-iface[1].key`" = "" ];then
    ##TODO
    if [ "$password_str" = "" ];then
        uci set wireless.@wifi-iface[1].key="1234567890"
    else
        uci set wireless.@wifi-iface[1].key="$password_str"
    fi
fi
if [ "`uci get wireless.@wifi-iface[2].key`" = "" ];then
    ##TODO
    if [ "$password_str" = "" ];then
        uci set wireless.@wifi-iface[2].key="1234567890"
    else
        uci set wireless.@wifi-iface[2].key="$password_str"
    fi
fi

uci commit wireless

