APP := wifimesh_datacollector

WIFIMESH_TOOLKIT := /opt/toolchains/OpenWrt-Toolchain-ar71xx-generic_gcc-4.8-linaro_uClibc-1.0.14.Linux-x86_64/toolchain-mips_74kc_gcc-4.8-linaro_uClibc-1.0.14

SYS_ROOT := $(WIFIMESH_TOOLKIT)/
INC_ROOT := $(WIFIMESH_TOOLKIT)/

CPP := $(SYS_ROOT)/bin/mips-openwrt-linux-g++
CC := $(SYS_ROOT)/bin/mips-openwrt-linux-gcc
LD := $(SYS_ROOT)/bin/mips-openwrt-linux-gcc

INCLUDE:= -I. -Iinc -Ideps -I$(INC_ROOT)/usr/include/ -Iinclude

# CFLAGS := -fPIC -w -pthread -std=c99 --sysroot=$(INC_ROOT) -DHAVE_CONFIG_H -DUSE_GLIB -I. -I.. -D__packed__=-DFEATURE_DATA_LOG_STDERR -Wundef -Wstrict-prototypes -Wno-trigraphs -g -O0 -fno-inline -fno-short-enums -O2 -shared -fexpensive-optimizations -frename-registers -fomit-frame-pointer -fforward-propagate -I$(INC_ROOT)/usr/include
# CFLAGS := -fPIC -w -pthread -std=c99 --sysroot=$(INC_ROOT) -DHAVE_CONFIG_H -DUSE_GLIB -I. -I.. -D__packed__=-DFEATURE_DATA_LOG_STDERR -Wundef -Wstrict-prototypes -Wno-trigraphs -g -O0 -fno-inline -fno-short-enums -O2 -shared -fexpensive-optimizations -frename-registers -fomit-frame-pointer -fforward-propagate -I$(INC_ROOT)/usr/include -DENABLE_SSL_HANDSHAKE

CFLAGS := -fPIC -w -pthread -std=c99 --sysroot=$(INC_ROOT) -I. -I.. -D__packed__=-DFEATURE_DATA_LOG_STDERR -Wundef -Wstrict-prototypes -Wno-trigraphs -g -O0 -fno-inline -fno-short-enums -O2 -shared -fexpensive-optimizations -frename-registers -fomit-frame-pointer -fforward-propagate -I$(INC_ROOT)/usr/include
# CFLAGS := -fPIC -w -pthread -std=c99 --sysroot=$(INC_ROOT) -I. -I.. -D__packed__=-DFEATURE_DATA_LOG_STDERR -Wundef -Wstrict-prototypes -Wno-trigraphs -g -O0 -fno-inline -fno-short-enums -O2 -shared -fexpensive-optimizations -frename-registers -fomit-frame-pointer -fforward-propagate -I$(INC_ROOT)/usr/include -DENABLE_SSL_HANDSHAKE

CPPFLAGS := -fPIC -w -pthread --sysroot=$(INC_ROOT) -DHAVE_CONFIG_H -DUSE_GLIB -I. -I.. -D__packed__= -DFEATURE_DATA_LOG_STDERR -Wundef -Wstrict-prototypes -Wno-trigraphs -g -O0 -fno-inline -fno-short-enums -O2 -shared -fexpensive-optimizations -frename-registers -fomit-frame-pointer -fforward-propagate -I$(INC_ROOT)/usr/include
# CPPFLAGS := -fPIC -w -pthread --sysroot=$(INC_ROOT) -I. -I.. -D__packed__= -DFEATURE_DATA_LOG_STDERR -Wundef -Wstrict-prototypes -Wno-trigraphs -g -O0 -fno-inline -fno-short-enums -O2 -shared -fexpensive-optimizations -frename-registers -fomit-frame-pointer -fforward-propagate -I$(INC_ROOT)/usr/include -DENABLE_SSL_HANDSHAKE

LDFLAGS1 :=  --sysroot=$(INC_ROOT) -L$(INC_ROOT)/usr/lib

LDFLAGS2 := -lpthread -lm -lrt -lcrypto -lssl -Llibs -ljiot-paho-mqtt-ws -ljiot-client-mqtt

DEPS = $(wildcard deps/*/*.c)
OBJS += $(DEPS:.c=.o)

SRC  = $(wildcard *.c)
OBJS += $(SRC:.c=.o)

all: $(APP)

$(APP): $(OBJS)
	$(LD) $(LDFLAGS1) $^ -o $@ $(LDFLAGS2)

%.o: %.c
	$(CC) -c $(INCLUDE) $(CFLAGS) $< -o $@

#%.o: %.cpp
#	$(CPP) -c $(INCLUDE) $(CPPFLAGS) $< -o $@

#clean:
#	@rm -f $(OBJS) $(APP)

CP      = cp -f
RM      = rm -f
MKDIR   = mkdir -p

clean:
	$(foreach c, $(APP), $(RM) $(c);)
	$(RM) $(OBJS)

